# Generated by Django 4.2 on 2024-05-21 08:16

from django.db import migrations, models
import django.db.models.deletion
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='games.comment'),
        ),
        migrations.AlterField(
            model_name='game',
            name='gamefile',
            field=models.FileField(upload_to=games.models.Game.upload_to_func),
        ),
        migrations.AlterField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='games', to='games.tag'),
        ),
    ]
